CC=/usr/bin/cc

compile: 
	$(CC) -c binary_search_tree.c

build:   
	$(CC) test.c binary_search_tree.c

test:
	$(CC) test.c binary_search_tree.c -o test
	./test

clean:
	rm -f binary_search_tree.o test a.out


